# Basic
name:               "NLIP Lab"
title:              "NLIP: Natural Language and Information Processing Lab" 
description:        "NLIP Lab is a young and dynamic research group as part of the Department of Computer Science and Engineering at Indian Institute of Technology Hyderabad. We are committed to pushing the frontiers of Natural Language Processing (NLP), Information Retrieval (IR), and related domains through cutting-edge research and development. We collaborate closely with academic institutions, industry partners, and other research groups to drive innovation in these fields. Our focus is on developing efficient and effective algorithms, models, and systems that can scale to real-world applications. We also strive to make our research accessible and impactful by publishing our findings in top-tier conferences and journals, and by open-sourcing our software and datasets."

# URL
url:                nlip-lab.github.io
baseurl:            
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

news_years: [2023, 2022, 2021, 2020, 2019]
publications_years: [2023, 2022, 2021, 2020, 2019, 2018, 2017]
image_count: 36

number_of_news_in_homepage: 4

last_updated: true

# Contact Details
address: "Academic Block-C, Lab C-309, IITH, Hyderabad, India"
office_hours: "Monday-Friday <br>(9.00am - 5.00pm)"
phone: "040-23018337"
email: "nlip@cse.iith.ac.in"

research_dropdown: true

# Navigation
nav:
  - name:           "home"
    href:           "/"

  - name:           "research"
    href:           "/research"

  - name:           "publications"
    href:           "/publication"

  - name:           "people"
    href:           "/people"

  - name:           "resources"
    href:           "/resources"

  - name:           "Gallery"
    href:           "/gallery"
    
  - name:           "Contact"
    href:           "/contact"
  # - name:           "about"
  #   href:           "/about"
  # - name:           "blog"
  #   href:           "/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"

collections:
  people:
    output: true
    permalink: /people/:title/index.html

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.


plugins:
  - jekyll/scholar
  - jekyll-redirect-from